name: Development CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install CI dependencies
        run: |
          pip install .[ci]
      - name: Lint
        run: |
          pylint src --fail-under=8 --disable=C0114 --disable=C0116 --disable=C0115 --disable=R1710
      - name: Check formatting with black
        uses: psf/black@stable
      - name: Test with tox
        run: |
          tox
      - name: Report on CodeCoverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage.xml
          name: codecov-pytown-model-name
      - name: Build wheel
        run: |
          python -m build
      # next step is to push the wheel into artifactory
